### PR TITLE
enhance: Repo refactor

### PR DESCRIPTION
**Pull request by LaurenceJJones**
~This PR is just simple QOL and improve debugging by allowing either debug or gin debug flags to be given.~

~As with current debug stuff if you set gin debug or debug you would miss some debugging so now its a single variable.~

This PR is now a refactoring of the repository to split code in multiple packages to not have a "single" package main that makes debugging stuff like leaks harder to trace since they all fall under "main".

TODO: currently when debug is enabled the route `/api/push` has been commented out temporarily since the pusher is now its own entity it does not access to controller, if we need to expose this we can pass the pusher instance to the controller, however, I want to ensure this debug route is useful enough to have to work round this.

### CODE REVIEW

**Comment by andrasbacsai** [comment]
Thanks for the PR! I will take a look.

Btw, not related to this issue, but the latest next version has a potential memory leak problem. Before our changes, it used 18-20MB of RAM. Now it is growing and it is over 50MB. 

This needs to be fixed, before the first release.

**Comment by LaurenceJJones** [comment]
Hold fire merging this PR, I am using this branch for the project restructure also.

**Comment by andrasbacsai** [comment]
(Btw, the memory usage is good now.)

**Comment by LaurenceJJones** [comment]
question: is `/api/push` actually useful to expose via the http server when in debug mode? cause of restructure its a little tricky to expose same functionality but can be done.

**Comment by LaurenceJJones** [comment]
Note this is currently hard to test, so I'll let @andrasbacsai let me know if I wrecked it :D

**Comment by andrasbacsai** [comment]
> question: is `/api/push` actually useful to expose via the http server when in debug mode? cause of restructure its a little tricky to expose same functionality but can be done.

No, that endpoint was required for testing in the early stages. Now it is obsolete.

**Comment by LaurenceJJones** [comment]
> > question: is `/api/push` actually useful to expose via the http server when in debug mode? cause of restructure its a little tricky to expose same functionality but can be done.
> 
> No, that endpoint was required for testing in the early stages. Now it is obsolete.

Awesome I can remove that when I get chance.

**Comment by andrasbacsai** [comment]
> > > question: is `/api/push` actually useful to expose via the http server when in debug mode? cause of restructure its a little tricky to expose same functionality but can be done.
> > 
> > 
> > No, that endpoint was required for testing in the early stages. Now it is obsolete.
> 
> Awesome I can remove that when I get chance.

I will remove it, because I also need to change a few things. Thanks for the refactor! It is huge!

**Comment by LaurenceJJones** [comment]
I guess by the merge it works 😅

**Pull request merged**
